# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: 'Bundles/com.ampstudios.scouts-$(build.buildNumber).aab'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*droid*.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'
    clean: true
    msbuildVersionOption: latest

- task: AndroidSigning@3
  inputs:
    apkFiles: 'outputDirectory'
    apksignerKeystoreFile: 'Scouts.keystore'
    apksignerKeystorePassword: 'aviaolegoA55'
    apksignerKeystoreAlias: 'Scouts'
    apksignerKeyPassword: 'aviaolegoA55'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'Bundles/com.ampstudios.scouts-$(build.buildNumber).aab'
    ArtifactName: 'com.ampstudios.scouts-$(build.buildNumber)'
    publishLocation: 'Container'